apiVersion: v1
kind: Namespace
metadata:
  name: medrano-luis-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: medrano-luis-configmap
  namespace: medrano-luis-namespace
data:
  opinion.log: |
    Su apreciación al curso que venimos desarrollando
---
apiVersion: v1
kind: Secret
metadata:
  name: medrano-luis-secret
  namespace: medrano-luis-namespace
type: Opaque
data:
  apellido_paterno: TWVkcmFubw==  # "Medrano" codificado en base64
  apellido_materno: R2FtYXJyYQ==  # "Gamarra" codificado en base64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medrano-luis-deployment
  namespace: medrano-luis-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: scale-flask
  template:
    metadata:
      labels:
        app: scale-flask
    spec:
      containers:
      - name: scale-flask
        image: tu_usuario_dockerhub/scale-flask-modificado:latest
        env:
        - name: SECRET_APELLIDO_PATERNO
          valueFrom:
            secretKeyRef:
              name: medrano-luis-secret
              key: apellido_paterno
        - name: SECRET_APELLIDO_MATERNO
          valueFrom:
            secretKeyRef:
              name: medrano-luis-secret
              key: apellido_materno
        volumeMounts:
        - name: config-volume
          mountPath: /app/logs
          subPath: opinion.log
      volumes:
      - name: config-volume
        configMap:
          name: medrano-luis-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: medrano-luis-service
  namespace: medrano-luis-namespace
spec:
  type: LoadBalancer
  selector:
    app: scale-flask
  ports:
  - port: 80
    targetPort: 5000
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: medrano-luis-cronjob
  namespace: medrano-luis-namespace
spec:
  schedule: "*/4 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: curl-container
            image: curlimages/curl:latest
            args:
            - curl
            - -s
            - http://medrano-luis-service.medrano-luis-namespace.svc.cluster.local
          restartPolicy: OnFailure
